---
title: "GLM Projections"
output:
  html_notebook: 
    theme: readable
  html_document: default
editor_options: 
  chunk_output_type: inline
---

## Build model
```{r}
model_input <- playerbox %>% filter(fdfp >= 0)
glm_model <- glm(
  fdfp ~ player_full_name + opp_team + venue_r_h,
  data = model_input,
  family = quasipoisson
)
glm_tidy <- broom::tidy(glm_model) %>% 
  dplyr::filter(p.value <= 0.05) %>%
  dplyr::arrange(desc(estimate))
```

## Run the predictions
```{r}
missing <- salaries %>% 
  anti_join(playerbox, by = c("Nickname" = "player_full_name"))
aug_salaries <- salaries %>% 
  semi_join(playerbox, by = c("Nickname" = "player_full_name")) %>%
  left_join(decoder, by = c("Team" = "fanduel")) %>%
  left_join(decoder, by = c("Opponent" = "fanduel")) %>%
  rename(
    player_full_name = Nickname,
    own_team = bigdataball.x,
    opp_team = bigdataball.y,
    venue_r_h = Venue)
aug_salaries <- aug_salaries %>%
  mutate(
    projection = round(predict(
      glm_model, newdata = aug_salaries, type = "response"), 2),
    value = round(1000 * projection / Salary.x, 2),
    pct_delta = round(projection / FPPG - 1, 2)
  ) %>%
  arrange(desc(projection))
fd_summary <- aug_salaries %>%
  select(
    player_full_name,
    Position,
    Played,
    Salary.x,
    FPPG,
    projection,
    value,
    pct_delta
  )
View(fd_summary)
```

## DraftKings predictions
```{r}
dk_glm_model <- glm(
  dkfp ~ player_full_name + opp_team + venue_r_h,
  data = model_input,
  family = quasipoisson
)
dk_glm_tidy <- broom::tidy(dk_glm_model) %>% 
  dplyr::filter(p.value <= 0.05) %>%
  dplyr::arrange(desc(estimate))
aug_salaries <- aug_salaries %>%
  mutate(
    dk_projection = round(predict(
      dk_glm_model, newdata = aug_salaries, type = "response"), 2),
    dk_value = round(1000 * dk_projection / Salary.y, 2),
    dk_pct_delta = round(dk_projection / AvgPointsPerGame - 1, 2)
  ) %>%
  arrange(desc(dk_projection))
dk_summary <- aug_salaries %>%
  select(
    player_full_name,
    Position,
    Played,
    Salary.y,
    AvgPointsPerGame,
    dk_projection,
    dk_value,
    dk_pct_delta
  )
View(dk_summary)
```

