---
title: "Data Loader"
output:
  html_notebook: 
    theme: readable
  html_document: default
editor_options: 
  chunk_output_type: inline
---
## Libraries
```{r message=FALSE}
library(MASS)
library(dfstools)
library(tidyverse)
library(stringr)
library(broom)
library(archetypes)
library(DT)

decoder <- tribble(
  ~fanduel, ~bigdataball,
  "MIN", "Minnesota",
  "DAL", "Dallas",
  "WAS", "Washington",
  "SEA", "Seattle",
  "NY", "New York",
  "IND", "Indiana",
  "PHO", "Phoenix",
  "LA", "Los Angeles",
  "ATL", "Atlanta",
  "CON", "Connecticut",
  "CHI", "Chicago",
  "SA", "San Antonio"
)
```
## Get data
```{r}
playerbox <- playerboxscore(
    "~/Dropbox/17-wnba-player/wnba-season-player-feed-07-09-2017.xlsx"
)
gamebox <- gameboxscore(playerbox)
salaries <- read_csv(
  "/home/Projects/draftkings/contest-standings/wnba/20170712/FanDuel-WNBA-2017-07-12-20052-players-list.csv",
  col_types = cols(
    X14 = col_skip(),
    X15 = col_skip()
  )
) %>%
  mutate(
    Road = (Game %>% sub(pattern = "@.*$", replacement = "")),
    Home = (Game %>% sub(pattern = "^.*@", replacement = "")),
    Venue = ifelse(Team == Road, "R", "H")
  )
dk_salaries <- read_csv(
  "/home/Projects/draftkings/contest-standings/nba/20170712/DKSalaries.csv") %>%
  select(Name, Salary, AvgPointsPerGame)
salaries <- salaries %>%
  full_join(dk_salaries, by = c("Nickname" = "Name")) %>%
  filter(!is.na(FPPG))

games <- salaries$Game %>%
  unique() %>%
  str_split_fixed(pattern = "@", n = 2) %>%
  as_tibble() %>%
  left_join(decoder, by = c("V1" = "fanduel")) %>%
  left_join(decoder, by = c("V2" = "fanduel")) %>%
  select(away = bigdataball.x, home = bigdataball.y)
```
