---
title: "WNBA Ranking"
output:
  html_notebook: 
    theme: readable
  html_document: default
editor_options: 
  chunk_output_type: inline
---

## Libraries
```{r message=FALSE}
# devtools::install(
#   "~/Projects/Mastering-DFS-Analytics/dfstools/",
#   build_vignettes = TRUE
# )
library(dfstools)
library(archetypes)
library(DT)
library(tibble)
library(dplyr)
library(ggtern)
library(readr)
```

## Get data
```{r}
playerbox <- playerboxscore(
    "~/Dropbox/17-wnba-player/wnba-season-player-feed-06-09-2017.xlsx"
)
gamebox <- gameboxscore(playerbox)
```

## Collect model input
```{r}
game_data <- collect_game_data(gamebox, 200, '2017-06-09')
```

## Build model
```{r}
season_model <- build_model(game_data)
```

## Back-predict for a test
```{r}
back_prediction <- game_predict(season_model, game_data)
backp_score_table <- rank_scores(back_prediction)
```

## get the new rows
```{r}
salaries <- read_csv(
  "/home/Projects/draftkings/contest-standings/wnba/20170611/FanDuel-WNBA-2017-06-11-19683-players-list.csv",
  col_types = cols(
    X14 = col_skip(),
    X15 = col_skip()
  )
)
decoder <- tribble(
  ~fanduel, ~bigdataball,
  "MIN", "Minnesota",
  "DAL", "Dallas",
  "WAS", "Washington",
  "SEA", "Seattle",
  "NY", "New York",
  "IND", "Indiana",
  "PHO", "Phoenix",
  "LA", "Los Angeles",
  "ATL", "Atlanta",
  "CON", "Connecticut",
  "CHI", "Chicago",
  "SA", "San Antonio"
)
new_rows <- salaries$Game %>%
  unique() %>%
  stringr::str_split_fixed(pattern = "@", n = 2) %>%
  as_tibble() %>%
  left_join(decoder, by = c("V1" = "fanduel")) %>%
  left_join(decoder, by = c("V2" = "fanduel")) %>%
  select(away = bigdataball.x, home = bigdataball.y)
prediction <- game_predict(season_model, new_rows)
View(prediction)
score_table <- rank_scores(prediction)
View(score_table)
```
