---
title: "WNBA Archetypes"
output:
  html_notebook: 
    theme: readable
  html_document: default
editor_options: 
  chunk_output_type: inline
---
## Libraries
```{r message=FALSE}
# devtools::install(
#   "~/Projects/Mastering-DFS-Analytics/dfstools/",
#   build_vignettes = TRUE
# )
library(dfstools)
library(archetypes)
library(DT)
library(tibble)
library(dplyr)
library(Rmixmod)
library(ggtern)
library(readr)
library(broom)
```
## Get data
```{r}
playerbox <- playerboxscore(
  "~/Dropbox/17-wnba-player/wnba-season-player-feed-06-09-2017.xlsx"
)
```

## Run model
```{r message=FALSE, error=FALSE, warning=FALSE}
arch_search <- archetype_search(playerbox)
screeplot(arch_search$arch_results)
```

## Look at the three-archetype result in detail

### Parallel coordinate plot with the archetypes
```{r}
old_par <- par(las = 2)
best_model <- bestModel(arch_search$arch_results[[3]])
archetype_table <- round(t(parameters(best_model)), 1) %>%
  as.data.frame() %>%
  rownames_to_column()
pcplot(
  best_model, 
  arch_search$arch_input$pbs_summary, 
  atypes.col = c("red", "dark green", "blue"))
par(old_par)
```
### Name the archetypes
```{r}
colnames(archetype_table)[1] <- "Metric"

# The one with the fewest minutes we'll call "Bench"
minutes <- as.vector(filter(archetype_table, Metric == "min"))[2:4]
ixbench <- which.min(minutes) + 1
colnames(archetype_table)[ixbench] <- "Bench"

# The one with the most rebounds we'll call "Front" (frontcourt)
rebounds <- as.vector(filter(archetype_table, Metric == "tot"))[2:4]
ixfront <- which.max(rebounds) + 1
colnames(archetype_table)[ixfront] <- "Front"

# The one with the most threes we'll call "Back"
threes <- as.vector(filter(archetype_table, Metric == "x3p"))[2:4]
ixback <- which.max(threes) + 1
colnames(archetype_table)[ixback] <- "Back"

# Show 'em!
datatable(archetype_table, rownames = FALSE, filter = "top")
```
### Player table
```{r}
pbs_summary <- arch_search$arch_input$pbs_summary %>%
  as_tibble() %>%
  mutate(fdfp_per_g = round(fdfp / games, 2))
fantasy_points <- pbs_summary %>%
  as_tibble() %>%
  select(fdfp:fdfp_per_g)
player_table <- bind_cols(
  arch_search$arch_input$current_team,
  coefficients(best_model, "alphas") %>% round(3) %>% as_tibble(),
  fantasy_points
) %>%
  arrange(desc(fdfp))
colnames(player_table)[1:3] <- c("Player", "Position", "Team")
colnames(player_table)[4:6] <- colnames(archetype_table)[2:4]
datatable(player_table, rownames = FALSE, filter = "top")
```
## Top Twelve
```{r}
top_twelve <- player_table %>% 
  top_n(12, fdfp_per_g)
plot <- ternary_plot(
  player_table = top_twelve, 
  plot_title = "WNBA Top Twelve")
print(plot)
filename <- "top_twelve.pdf"
ggtern::ggsave(filename, width = 11, height = 8.5, units = "in")
```
## Player clusters
```{r}
front_back_cluster <- mixmodCluster(
  dplyr::select(player_table, Front, Back, fdfp_per_g), 1:12
)
plot(front_back_cluster)
front_back_model <- glm(
  fdfp_per_g ~ Front + Back, 
  data = (player_table %>% filter(Bench < 0.5)),
  family = quasipoisson
)
summary(front_back_model)
print(anova(front_back_model))
bench_cluster <- mixmodCluster(
  dplyr::select(player_table, Bench, fdfp_per_g) %>% 
    dplyr::filter(fdfp_per_g > 5), 1:12)
plot(bench_cluster)
```
## Generate team plots
```{r}
for (t in player_table$Team %>% unique()) {
  team_data <- player_table %>% 
    filter(Team == t) %>% top_n(12, fdfp)
  plot <- ternary_plot(
    player_table = team_data, 
    plot_title = t)
  print(plot)
  filename <- paste(t, "pdf", sep = ".")
  ggtern::ggsave(filename, width = 11, height = 8.5, units = "in")
}
```
## Projection model
```{r}
projection_input <- playerbox %>%
  full_join(
    {player_table %>% select(Player, Bench, Back, Front, games)},
    by = c("player_full_name" = "Player")) %>%
  filter(fdfp >= 0) %>%
  select(date:min, fdfp, Bench:Front, games = games.y)

points_model <- glm(
  fdfp ~ player_full_name + opp_team + venue_r_h,
  data = projection_input,
  family = quasipoisson)
points_tidy <- tidy(points_model) %>%
  filter(p.value <= 0.05) %>%
  arrange(desc(estimate))
View(points_tidy)

minutes_model <- glm(
  min ~ player_full_name + opp_team + venue_r_h,
  data = projection_input,
  family = quasipoisson)
minutes_tidy <- tidy(minutes_model) %>%
  filter(p.value <= 0.05) %>%
  arrange(desc(estimate))
View(minutes_tidy)
```
