#! /bin/bash

# Uninstall any old versions
echo "Removing any old Docker packages"
echo "You can ignore errors"
sudo yum remove docker \
  docker-common \
  container-selinux \
  docker-selinux \
  docker-engine \
  docker-compose

# Set up the Docker CE repository on CentOS:
echo "Adding the Docker CE repository"
sudo yum install -y yum-utils
sudo yum-config-manager \
  --add-repo \
  https://download.docker.com/linux/centos/docker-ce.repo
sudo yum makecache fast

# Install the latest version of Docker CE on CentOS:
echo "Installing Docker CE"
sudo yum -y install \
  docker-ce

# Start Docker:
echo "Enabling and starting Docker"
sudo systemctl enable docker
sudo systemctl start docker

# Test your installation:
echo "Testing it!"
sudo docker run hello-world

# Configure "docker" group
echo "Adding ${USER} to the 'docker' group"
sudo groupadd docker
sudo usermod -aG docker ${USER}
echo "Log out and back in to join the 'docker' group."
